name: formito
favicon: null
layout_spectrum: 0.87765
typography_spectrum: 0.64836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25c8b4'
    - '#4a4a4a'
    - '#000000'
    - '#808080'
    - '#008080'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
